# Basic behavior
set -g default-terminal "screen-256color"
set -g terminal-overrides ',xterm:colors=256'
set -s escape-time 0
set-option -g history-limit 10000
set -g base-index 1
setw -g pane-base-index 1

# Prefix and copy mode
set -g prefix C-q
set-window-option -g mode-keys vi
setw -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
