# Key bindings
bind r source-file ~/.tmux.conf \; display "Reloaded!"

bind -r l next-window
bind -r h previous-window
bind c new-window -c '#{pane_current_path}'
bind '\' split-window -h
bind - split-window -v
bind z resize-pane -Z
set-option -g renumber-windows on
bind -r Left run 'cw=$(tmux display-message -p \#I) && [ $cw -gt 0 ] && tmux swap-window -s $cw -t $(($cw - 1))'
bind -r Right run 'cw=$(tmux display-message -p \#I) && tmux swap-window -s $cw -t $(($cw + 1))'
