# Pane labels and borders
set-option -g pane-border-status top
set-option -g pane-border-lines double
setw -g pane-border-format '#{?pane_active,#[fg=#101820]#[bg=#5fff87]#[bold],#[fg=colour245]} #P | #{pane_current_command} | #{pane_current_path} #[default]'
