# Status line
set-option -g status-interval 1
set-option -g status-position top
set-option -g status-justify "centre"
set-option -g status-left-length 15
set-option -g status-left "#[fg=default,bg=default]Session: #S #[default]"
set-window-option -g window-status-format " #I: #W "
set-window-option -g window-status-current-format "#[fg=#101820,bg=#ae8b2d,bold] #[reverse] #I #[noreverse] #W #[default]"
set-option -g status-right-length 120
set-option -g status-right "#[fg=default,bg=default] Mem: #(${HOME}/.bin/tmux-status-mem) | LA: #(${HOME}/.bin/tmux-status-load) | %Y/%m/%d %H:%M:%S#[default]"
